import { Inter } from "next/font/google";
import "../globals.css";
import { MainHeader } from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function NavigationRootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
      </head>
      <body className={inter.className}>
        <div className="pt-4">
          <MainHeader />
        </div>
        <div className="my-7">{children}</div>
      </body>
    </html>
  );
}
